name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Upload to CoPilot
      run: bash <(curl -s https://copilot.blackducksoftware.com/ci/githubactions/scripts/upload)
